import type { WhisperMessage } from '../../transcription/types';
import type { RDSMessage, POCSAGMessage } from '../../worker/runtime/types';
import type { DSDStatus } from '../../worker/decoders/dsd/types';
import type { ReceiverCommand } from '../../remote/types';
import type { AppInstance } from './instance';
import type { Rtl433Protocol, Rtl433Message } from '../../worker/decoders/rtl433';

export interface ReceiverMethods {
	copyRemoteLink(): void;
	togglePanel(key: string): void;
	toggleBookmarkCategory(collKey: string): void;
	formatFreq(mhz?: number): string;
	formatActivityDuration(ms: number): string;
	resetActivityStats(): void;
	vfoColor(index: number): string;
	vfoTint(index: number): string;
	vfoBookmarkLabel(i: number): string | null;
	focusVfoFreq(index: number): void;
	focusActivityVfo(index: number): void;
	labelFreq(percent: number): string;
	showMsg(msg: string): void;
	toggleSidebar(): void;
	closeSidebar(): void;
	unlockAndConnect(): void;
	_initAudioCtx(): void;
	_createSilentAudioEl(): HTMLAudioElement;
	connect(): Promise<void>;
	pairNewDevice(): Promise<void>;
	connectToDevice(device: USBDevice): Promise<void>;
	_connectToDevice(device: USBDevice, deviceIndex?: number): Promise<void>;
	connectMock(): Promise<void>;
	_connectMock(): Promise<void>;
	disconnect(): Promise<void>;
	_disconnectReceiver(): Promise<void>;
	_releaseWakeLock(): void;
	_acquireWakeLock(): Promise<void>;
	togglePlay(isRestart?: boolean): Promise<void>;
	_togglePlay(isRestart?: boolean): Promise<void>;
	startStream(isRestart?: boolean): Promise<void>;
	initCanvas(): void;
	resizeFftCanvas(): void;
	drawSpectrum(data: Float32Array): void;
	playAudio(samples: Float32Array | Record<number, number>): void;
	_scheduleAudioChunk(floats: Float32Array): void;
	clearInactiveSoloAudio(): void;
	toggleSoloAudio(index: number): void;
	toggleVfoCheckbox(index: number): void;
	applyVfoFreq(e: Event, index: number): void;
	applyModeDefaults(index: number): void;
	updateBackendVfoParams(index: number): void;
	addVfo(): Promise<void>;
	isFreqInBandwidth(freq: number): boolean;
	findCenterForAllVfos(newFreq: number, vfoIndex: number): number | null;
	findBestCenterForSubset(newFreq: number, vfoIndex: number): { centerFreq: number; included: number[]; excluded: number[] };
	validateAndApplyVfoFreq(index: number, newFreq: number): void;
	updateAllBackendVfoParams(): void;
	resolveVfoConflict(choice: 'a' | 'b' | 'cancel'): void;
	autoSquelch(index: number): void;
	removeVfo(index: number): Promise<void>;
	saveSetting(): void;
	loadSetting(useLegacy?: boolean): void;
	requestOrApplyChange(target: string, property: string, value: number): void;
	categoryLabel(value: string | number): string;
	openSaveBookmark(type: string): void;
	confirmBookmark(): void;
	jumpToBookmark(index: number): Promise<void>;
	openEditBookmark(index: number): void;
	confirmEditBookmark(): void;
	addVfoToEditGroup(): void;
	deleteBookmark(index: number): void;
	saveBookmarks(): void;
	exportBookmarks(): void;
	importBookmarks(event: Event): void;
	confirmImport(mode: string): void;
	loadBookmarks(): void;
	flushInactiveWhisperVfos(): void;
	benchmarkWhisper(): void;
	toggleTranscriptPanel(): void;
	toggleWhisper(): Promise<void>;
	startWhisper(): Promise<void>;
	stopWhisper(): void;
	_onWhisperMessage(e: MessageEvent<WhisperMessage>): void;
	_feedWhisperVfo(vfoIndex: number, freqMhz: number, samples48k: Float32Array): void;
	_flushWhisperVfoBuf(vfoIndex: number): void;
	clearTranscript(): void;
	exportTranscript(): void;
	togglePocsagPanel(): void;
	_onPocsagMessage(vfoIndex: number, freqMhz: number, msg: POCSAGMessage): void;
	clearPocsag(): void;
	exportPocsag(): void;
	_onDsdStatus(vfoIndex: number, status: DSDStatus): void;
	_rdsStation(vfoIndex: number): AppInstance['rds']['stations'][number];
	rdsActive(): AppInstance['rds']['stations'][number];
	_onRdsMessage(vfoIndex: number, freqMhz: number, msg: RDSMessage): void;
	toggleDisplayLock(): void;
	handleWheelZoom(e: WheelEvent, rect: DOMRect): void;
	applyZoomToEngine(): void;
	applySharedChannelization(): void;
	startRemoteHost(): Promise<void>;
	connectRemoteClient(hostId: string): Promise<void>;
	regenerateShareCode(): Promise<void>;
	connectToRemoteId(id: string): Promise<void>;
	removeRecentRemoteId(id: string): void;
	handleRemoteCommand(clientIdOrCmd: string | ReceiverCommand, cmdOrUndefined?: ReceiverCommand): void;
	kickRemoteClient(clientId: string): void;
	remoteClientDuration(connectedAt: number): string;
	autoGainSupported(): boolean;
	autoGainControls(): string;
	cancelAutoGain(): void;
	autoSetGains(): Promise<void>;
	toggleRtl433Panel(): void;
	_onRtl433Message(index: number, freq: number, msg: Rtl433Message): void;
	rtl433StatusText(index: number): string;
	formatRtl433Event(event: Record<string, unknown>): string;
	filteredRtl433Protocols(): Rtl433Protocol[];
	clearRtl433(): void;
	exportRtl433(): void;
}
