import type { BleMessage } from '@/worker/decoders/ble/types';
import type { AisMessage } from '@/worker/decoders/ais/types';
import type { AdsbMessage } from '@/worker/decoders/adsb/types';
import type { WhisperChunkMeta, WhisperVfoState } from '@/app/decoders/whisper.types';
import type { WatchOptions, WatchStopHandle } from 'vue';
import type { Remote } from 'comlink';
import type { Backend } from '@/worker/runtime/backend';
import type { createAppData } from './state';
import type { Waterfall, WaterfallGL } from '@/display/utils';
import type { SpectrumFrameLimiter, WaterfallClock } from '@/display/spectrum-rate';
import type { WebRTCHandler } from '@/remote/webrtc';
import type { ReceiverTransport } from '@/remote/receiver-transport';
import type { Vfo } from './types';
import type { WorkspaceInstance } from '@/app/workspace/types';
import type { WhisperMessage } from '@/transcription/types';
import type { RDSMessage, POCSAGMessage, Rtl433Protocol, Rtl433Message } from '@/worker/decoders/types';
import type { DSDStatus } from '@/worker/decoders/dsd/types';
import type { ReceiverCommand } from '@/remote/types';

export interface ReceiverInternals {
	receiverId: string;
	settingsKey: string;
	workspace: WorkspaceInstance | null;
	backend: Remote<Backend>;
	$el: HTMLElement;
	$refs: Record<string, HTMLElement> & { fft: HTMLCanvasElement; waterfall: HTMLCanvasElement; bookmarkNameInput: HTMLInputElement };
	$nextTick(callback?: () => void): Promise<void>;
	$watch<T>(source: (() => T) | string, callback: (value: T, previous: T) => void | Promise<void>, options?: WatchOptions): WatchStopHandle;
	activeAudioVfos: Array<{ index: number; vfo: Vfo }>;
	minFreq: number;
	maxFreq: number;

	audioCtx: AudioContext | null;
	gainNode: GainNode | null;
	audioRingBuf: Float32Array;
	audioRingPos: number;
	audioRingChannels?: 1 | 2;
	audioRingSize: string;
	queuedAudioSched: string;
	nextPlayTime: number;
	_audioWorklet?: AudioWorkletNode | null;
	_audioWorkletReady?: Promise<void> | null;
	_audioPlaybackPaused?: boolean;
	renderSize: number;
	_fftCtx: CanvasRenderingContext2D;
	_waterfallEngine: (Waterfall | WaterfallGL) & { destroy?: () => void };
	_waterfallClock: WaterfallClock;
	_remoteSpectrumLimiter: SpectrumFrameLimiter;
	_lastSpectrumData?: Float32Array;
	_zoomRepaint?: boolean;
	_lastFrameTime: number;
	_framesDrawn: number;
	_mediaAudioEl: HTMLAudioElement | null;
	_mediaSource: MediaSource | null;
	_silentMp3Data: ArrayBuffer | null;
	_wakeLock: WakeLockSentinel | null;
	_statsTimer: ReturnType<typeof setInterval> | null;
	_backendWorker?: Worker;
	_whisperWorker: Worker | null;
	_whisperBenchmarkAudio?: Float32Array;
	_whisperBenchmarkModel?: string;
	_whisperChunkId: number;
	_whisperChunkMeta: Record<number, WhisperChunkMeta>;
	_whisperVfoStates: Record<number, WhisperVfoState>;
	_webrtc: WebRTCHandler | ReceiverTransport | null;
	_receiverTransport: ReceiverTransport | null;
	_cleanup: Array<() => void>;
	_canvasCleanup?: () => void;
	_disposeHeaderTools?: () => void;
	_disposed?: boolean;
	_removing?: boolean;
	_connectingDevice?: boolean;
	_playChanging?: boolean;
	_disconnecting?: boolean;
	_applyingSync?: boolean;
	_hostRunning?: boolean;
	_resumeAfterHostPause?: boolean;
	_pendingImportFile: File | null;
}

export type AppInstance = Omit<ReturnType<typeof createAppData>, 'backend'> & ReceiverInternals & ReceiverMethods;

export interface ReceiverMethods {
	copyRemoteLink(): void;
	togglePanel(key: string): void;
	toggleBookmarkCategory(collKey: string): void;
	formatFreq(mhz?: number): string;
	formatActivityDuration(ms: number): string;
	resetActivityStats(): void;
	vfoColor(index: number): string;
	vfoTint(index: number): string;
	vfoBookmarkLabel(i: number): string | null;
	focusVfoFreq(index: number): void;
	focusActivityVfo(index: number): void;
	labelFreq(percent: number): string;
	showMsg(msg: string): void;
	toggleSidebar(): void;
	closeSidebar(): void;
	unlockAndConnect(): void;
	_initAudioCtx(): void;
	_createSilentAudioEl(): HTMLAudioElement;
	connect(): Promise<void>;
	pairNewDevice(): Promise<void>;
	connectToDevice(device: USBDevice): Promise<void>;
	_connectToDevice(device: USBDevice, deviceIndex?: number): Promise<void>;
	connectMock(): Promise<void>;
	_connectMock(): Promise<void>;
	disconnect(): Promise<void>;
	_disconnectReceiver(): Promise<void>;
	_releaseWakeLock(): void;
	_acquireWakeLock(): Promise<void>;
	togglePlay(isRestart?: boolean): Promise<void>;
	_togglePlay(isRestart?: boolean): Promise<void>;
	startStream(isRestart?: boolean): Promise<void>;
	initCanvas(): void;
	resizeFftCanvas(): void;
	drawSpectrum(data: Float32Array): void;
	playAudio(samples: Float32Array | Record<number, number>, channels?: 1 | 2): void;
	_scheduleAudioChunk(floats: Float32Array, channels?: 1 | 2): void;
	_prepareAudioWorklet(): Promise<void>;
	_resetAudioPlayback(clearCounters?: boolean): void;
	_disposeAudioWorklet(): void;
	clearInactiveSoloAudio(): void;
	toggleSoloAudio(index: number): void;
	toggleVfoCheckbox(index: number): void;
	applyVfoFreq(e: Event, index: number): void;
	applyModeDefaults(index: number): void;
	updateBackendVfoParams(index: number): void;
	addVfo(): Promise<void>;
	isFreqInBandwidth(freq: number): boolean;
	findCenterForAllVfos(newFreq: number, vfoIndex: number): number | null;
	findBestCenterForSubset(newFreq: number, vfoIndex: number): { centerFreq: number; included: number[]; excluded: number[] };
	validateAndApplyVfoFreq(index: number, newFreq: number): void;
	updateAllBackendVfoParams(): void;
	resolveVfoConflict(choice: 'a' | 'b' | 'cancel'): void;
	autoSquelch(index: number): void;
	removeVfo(index: number): Promise<void>;
	saveSetting(): void;
	loadSetting(useLegacy?: boolean): void;
	requestOrApplyChange(target: string, property: string, value: number): void;
	categoryLabel(value: string | number): string;
	openSaveBookmark(type: string): void;
	confirmBookmark(): void;
	jumpToBookmark(index: number): Promise<void>;
	openEditBookmark(index: number): void;
	confirmEditBookmark(): void;
	addVfoToEditGroup(): void;
	deleteBookmark(index: number): void;
	saveBookmarks(): void;
	exportBookmarks(): void;
	importBookmarks(event: Event): void;
	confirmImport(mode: string): void;
	loadBookmarks(): void;
	flushInactiveWhisperVfos(): void;
	benchmarkWhisper(): void;
	toggleTranscriptPanel(): void;
	toggleWhisper(): Promise<void>;
	startWhisper(): Promise<void>;
	stopWhisper(): void;
	_onWhisperMessage(e: MessageEvent<WhisperMessage>): void;
	_feedWhisperVfo(vfoIndex: number, freqMhz: number, samples48k: Float32Array): void;
	_flushWhisperVfoBuf(vfoIndex: number): void;
	clearTranscript(): void;
	exportTranscript(): void;
	togglePocsagPanel(): void;
	_onPocsagMessage(vfoIndex: number, freqMhz: number, msg: POCSAGMessage): void;
	clearPocsag(): void;
	exportPocsag(): void;
	_onDsdStatus(vfoIndex: number, status: DSDStatus): void;
	_rdsStation(vfoIndex: number): AppInstance['rds']['stations'][number];
	rdsActive(): AppInstance['rds']['stations'][number];
	_onRdsMessage(vfoIndex: number, freqMhz: number, msg: RDSMessage): void;
	toggleDisplayLock(): void;
	handleWheelZoom(e: WheelEvent, rect: DOMRect): void;
	applyZoomToEngine(): void;
	applySharedChannelization(): void;
	startRemoteHost(): Promise<void>;
	connectRemoteClient(hostId: string): Promise<void>;
	regenerateShareCode(): Promise<void>;
	connectToRemoteId(id: string): Promise<void>;
	removeRecentRemoteId(id: string): void;
	handleRemoteCommand(clientIdOrCmd: string | ReceiverCommand, cmdOrUndefined?: ReceiverCommand): void;
	kickRemoteClient(clientId: string): void;
	remoteClientDuration(connectedAt: number): string;
	autoGainSupported(): boolean;
	autoGainControls(): string;
	cancelAutoGain(): void;
	autoSetGains(): Promise<void>;
	toggleBlePanel(): void;
	_onBleMessage(index: number, freq: number, msg: BleMessage): void;
	tuneBleChannel(channel: number, index?: number): Promise<boolean>;
	startBleScan(): Promise<void>;
	stopBleScan(): void;
	clearBleDevices(): void;
	toggleAisPanel(): void;
	tuneAisVfo(frequency: number, index?: number): void;
	_onAisMessage(index: number, freq: number, msg: AisMessage): void;
	aisStatusText(index: number): string;
	toggleAdsbPanel(): void;
	tuneAdsbVfo(index?: number): void;
	_onAdsbMessage(index: number, freq: number, msg: AdsbMessage): void;
	adsbStatusText(index: number): string;
	toggleRtl433Panel(): void;
	_onRtl433Message(index: number, freq: number, msg: Rtl433Message): void;
	rtl433StatusText(index: number): string;
	formatRtl433Event(event: Record<string, unknown>): string;
	filteredRtl433Protocols(): Rtl433Protocol[];
	clearRtl433(): void;
	exportRtl433(): void;
}
