/* tslint:disable */
/* eslint-disable */

export class DspProcessor {
    free(): void;
    [Symbol.dispose](): void;
    /**
     * Returns the number of f32 samples generated by the last `process_iq_only_ptr` call.
     */
    get_iq_output_len(): number;
    get_output_channels(): number;
    /**
     * Returns the number of f32 samples generated by the last `process_ptr` call.
     */
    get_output_len(): number;
    /**
     * Returns the last measured signal level in dB (for auto-squelch calibration).
     */
    get_squelch_db(): number;
    /**
     * Create a new DSP processor matching SDR++ NFM pipeline.
     *
     * # Arguments
     * * `in_sample_rate` - Source sample rate (e.g. 2_000_000.0 for 2 MHz)
     * * `shift_hz` - Frequency offset in Hz (VFO offset from center)
     * * `bandwidth` - Channel bandwidth in Hz (default 12500.0 for NFM)
     */
    constructor(in_sample_rate: number, shift_hz: number, bandwidth: number);
    /**
     * Process raw i8 IQ samples through the full SDR++ NFM pipeline.
     * Returns the number of f32 audio samples written to `output`.
     *
     * Input: i8 IQ pairs [I0, Q0, I1, Q1, ...]
     * Output: f32 audio at 48 kHz; interleaved L/R when WFM stereo is enabled.
     */
    process(input: Int8Array, output: Float32Array): number;
    process_f32_ptr(pointer: number, count: number): number;
    /**
     * Process raw i8 IQ samples through NCO + decimation only.
     * Returns interleaved complex f32 IQ pairs at IF sample rate (50 kHz).
     * Used for non-FM modes (AM, SSB, CW, RAW) where JS handles demodulation.
     */
    process_iq_only(input: Int8Array, output: Float32Array): number;
    process_iq_only_f32_ptr(pointer: number, count: number): number;
    /**
     * Zero-copy process for IQ only using a raw pointer for input.
     */
    process_iq_only_ptr(iq_ptr: number, num_iq_bytes: number): number;
    /**
     * Zero-copy process using a raw pointer for IQ input and returning a raw pointer.
     */
    process_ptr(iq_ptr: number, num_iq_bytes: number): number;
    /**
     * Reset all DSP state (filter histories, demod phase, resampler state).
     * Call this when switching demodulation modes or when the signal chain
     * changes to avoid stale state causing audio artifacts.
     */
    reset(): void;
    /**
     * Enable or disable audio filters (LowPass, HighPass) for NFM.
     */
    set_audio_filters(low_pass: boolean, high_pass: boolean): void;
    /**
     * Update the channel bandwidth and rebuild filters.
     */
    set_bandwidth(bandwidth: number): void;
    /**
     * Change the IF sample rate and rebuild the entire resampler/filter chain.
     * SDR++ uses different IF rates per demodulator mode:
     *   NFM: 50,000 Hz,  WFM: 250,000 Hz,  AM: 15,000 Hz,
     *   USB/LSB/DSB: 24,000 Hz,  CW: 3,000 Hz
     */
    set_if_sample_rate(new_if_sr: number): void;
    /**
     * Update the NCO frequency offset.
     */
    set_shift(sample_rate: number, shift_hz: number): void;
    /**
     * Set squelch level in dB. Set to -200 or below to effectively disable.
     */
    set_squelch(level: number, enabled: boolean): void;
    /**
     * Stereo output is interleaved L/R; get_output_len counts float values.
     */
    set_stereo(enabled: boolean): void;
    /**
     * Enable or disable WFM mode. When enabled, uses SDR++ broadcast_fm.h
     * audio filter settings (15 kHz cutoff, 4 kHz transition) instead of
     * the standard bandwidth/2 cutoff used for NFM and other modes.
     */
    set_wfm_mode(enabled: boolean): void;
}

export class FFT {
    free(): void;
    [Symbol.dispose](): void;
    /**
     * Process raw i8 IQ samples and write power spectrum to `result`.
     *
     * Input: i8 IQ pairs [I0, Q0, I1, Q1, ...] — length must be at least 2 * n
     * Output: f32 power spectrum in dB, DC-centered, length `n`.
     * A bin-centered unit-amplitude tone with a rectangular window is 0 dB.
     * Window gain is retained, matching SDR++ (no coherent-gain correction).
     */
    fft(input_: Int8Array, result: Float32Array): void;
    /**
     * Zero-copy FFT: takes a raw pointer to i8 IQ data, returns a raw pointer to f32 output.
     * The returned pointer is valid until the next call to `fft` or `fft_ptr`.
     */
    fft_ptr(iq_ptr: number, num_iq_bytes: number): number;
    /**
     * Create a new FFT processor.
     *
     * # Arguments
     * * `n` - FFT size. Must be a power of two and greater than 0
     * * `window_` - Window function array. Length must equal `n`
     */
    constructor(n: number, window_: Float32Array);
    /**
     * Set smoothing speed (SDR++ semantics).
     * 1.0 = no smoothing (100% new value).
     * 0.0 = full smoothing (output frozen — 0% new value).
     */
    set_smoothing_speed(val: number): void;
}

export class SharedChannelizer {
    free(): void;
    [Symbol.dispose](): void;
    constructor(ratio: number, centers: Int32Array);
    output_len(band: number): number;
    output_ptr(band: number): number;
    process(input: Int8Array): void;
    set_batch_samples(count: number): void;
}

export function alloc_float_buffer(capacity: number): number;

export function alloc_iq_buffer(capacity: number): number;

export function free_iq_buffer(ptr: number, capacity: number): void;

export function set_panic_hook(): void;
