/** P25 Phase 1 C4FM framing, IMBE extraction and call metadata.
 * Layout checked against TIA-102 vectors generated by OP25 p25craft.py
 * and the status-symbol reader in szechyjs/dsd. All offsets are exact.
 */
import { P25_IW, P25_IX, P25_IY, P25_IZ, type DSDStatus } from './types';
import { golayDecode6, golayDecode12 } from './ecc/golay';
import { hammingDecode } from './ecc/hamming';
import { rsDecode_36_20_17, rsDecode_24_12_13, rsDecode_24_16_9 } from './ecc/reed-solomon';
import { decodeP25NID } from './ecc/p25-nid';

export const DUID_HDU = 0;
export const DUID_TDU = 3;
export const DUID_LDU1 = 5;
export const DUID_TSDU = 7;
export const DUID_LDU2 = 10;
export const DUID_PDU = 12;
export const DUID_TDULC = 15;
const DUID_NAMES: Record<number, string> = { 0: 'HDU', 3: 'TDU', 5: 'LDU1', 7: 'TSDU', 10: 'LDU2', 12: 'PDU', 15: 'TDULC' };

// Physical dibits, including status symbols, after the 24-dibit frame sync.
export const P25_NID_DIBITS = 33;
export const P25_LDU_BODY_DIBITS = 807;
export const P25_HDU_BODY_DIBITS = 339;
export const P25_TDULC_BODY_DIBITS = 159;
export const P25_TDU_BODY_DIBITS = 15;

export function p25FrameDibits(duid: number): number {
	switch (duid) {
		case DUID_LDU1: case DUID_LDU2: return 864 - 24;
		case DUID_HDU: return 396 - 24;
		case DUID_TDU: return 72 - 24;
		case DUID_TDULC: return 216 - 24;
		// Variable length control/data units: resume sync search after their NID.
		default: return P25_NID_DIBITS;
	}
}

/** Read payload dibits, dropping status at frame positions 35,71,... */
function payload(buf: Uint8Array, pos: number, frameOffset: number, count: number): Uint8Array {
	const result = new Uint8Array(count);
	for (let i = 0; i < count; i++, pos++, frameOffset++) {
		if (frameOffset % 36 === 35) { pos++; frameOffset++; }
		result[i] = buf[pos & 0xffff];
	}
	return result;
}
function bits(dibits: Uint8Array): Int8Array {
	return Int8Array.from({ length: dibits.length * 2 }, (_, i) => (dibits[i >> 1] >> (1 - (i & 1))) & 1);
}
function binToInt(data: Int8Array, offset: number, length: number): number {
	let result = 0;
	for (let i = 0; i < length; i++) result = (result << 1) | data[offset + i];
	return result;
}
export function parseP25NID(buf: Uint8Array, pos: number) {
	const nid = decodeP25NID(Uint8Array.from(bits(payload(buf, pos, 24, 32))));
	const nac = nid ? nid.data >>> 4 : 0;
	const duid = nid ? nid.data & 15 : -1;
	return { nac, duid, duidName: DUID_NAMES[duid] || 'UNK', valid: nid !== null, errors: nid?.errors };
}
/** Input contains 72 voice dibits with status symbols already removed. */
export function extractP25IMBE(buf: Uint8Array, pos: number): Int8Array {
	const frame = new Int8Array(184);
	for (let i = 0; i < 72; i++) {
		const dibit = buf[pos + i];
		frame[P25_IW[i] * 23 + P25_IX[i]] = (dibit >> 1) & 1;
		frame[P25_IY[i] * 23 + P25_IZ[i]] = dibit & 1;
	}
	return frame;
}

// LDU offsets after removing status: 648 voice +120 LC/ES +16 LSD dibits.
const VOICE_OFFSETS = [0, 72, 164, 256, 348, 440, 532, 624, 712];
const WORD_OFFSETS = [144, 236, 328, 420, 512, 604];
function ldu(buf: Uint8Array, pos: number) {
	const body = payload(buf, pos, 57, 784);
	const words = new Int8Array(144);
	for (let group = 0; group < 6; group++) for (let word = 0; word < 4; word++) {
		const data = bits(body.subarray(WORD_OFFSETS[group] + word * 5, WORD_OFFSETS[group] + word * 5 + 5));
		const hex = data.subarray(0, 6);
		hammingDecode(hex, data.subarray(6));
		words.set(hex, (23 - (group * 4 + word)) * 6);
	}
	return { frames: VOICE_OFFSETS.map(offset => extractP25IMBE(body, offset)), words };
}
/** RS helpers use reverse hex-word order, as in DSD's polynomial representation. */
function wireOrder(data: Int8Array): Int8Array {
	const result = new Int8Array(data.length);
	for (let i = 0; i < data.length / 6; i++) result.set(data.subarray(i * 6, i * 6 + 6), data.length - 6 - i * 6);
	return result;
}
function linkControl(data: Int8Array, status: DSDStatus): void {
	const format = binToInt(data, 0, 8);
	const mfid = binToInt(data, 8, 8);
	if ((format & 0x80) || mfid !== 0 || (format & 0x3f) !== 0) return;
	status.tg = binToInt(data, 32, 16);
	status.src = binToInt(data, 48, 24);
	status.emr = !!(binToInt(data, 16, 8) & 0x80);
	status.encrypted = !!(binToInt(data, 16, 8) & 0x40) || (status.algid != null && status.algid !== 0x80);
}
function encryption(data: Int8Array, algOffset: number, status: DSDStatus): void {
	status.algid = binToInt(data, algOffset, 8);
	status.kid = binToInt(data, algOffset + 8, 16);
	status.encrypted = status.algid !== 0x80;
}
export function processP25LDU1(buf: Uint8Array, pos: number, status: DSDStatus): Int8Array[] {
	const { frames, words } = ldu(buf, pos);
	const data = words.subarray(72);
	if (rsDecode_24_12_13(data, words.subarray(0, 72)) === 0) linkControl(wireOrder(data), status);
	return frames;
}
export function processP25LDU2(buf: Uint8Array, pos: number, status: DSDStatus): Int8Array[] {
	const { frames, words } = ldu(buf, pos);
	const data = words.subarray(48);
	if (rsDecode_24_16_9(data, words.subarray(0, 48)) === 0) encryption(wireOrder(data), 72, status);
	return frames;
}
export function processP25HDU(buf: Uint8Array, pos: number, status: DSDStatus): void {
	const body = bits(payload(buf, pos, 57, 324));
	const words = new Int8Array(216);
	for (let i = 0; i < 36; i++) {
		const word = body.subarray(i * 18, i * 18 + 18);
		const hex = word.subarray(0, 6);
		golayDecode6(hex, word.subarray(6));
		words.set(hex, (35 - i) * 6);
	}
	const data = words.subarray(96);
	if (rsDecode_36_20_17(data, words.subarray(0, 96)) !== 0) return;
	const header = wireOrder(data);
	encryption(header, 80, status);
	status.tg = binToInt(header, 104, 16);
}
export function processP25TDU(_buf: Uint8Array, _pos: number, status: DSDStatus): void {
	status.duid = 'TDU';
}
export function processP25TDULC(buf: Uint8Array, pos: number, status: DSDStatus): void {
	const body = bits(payload(buf, pos, 57, 144));
	const words = new Int8Array(144);
	for (let i = 0; i < 12; i++) {
		const word = body.subarray(i * 24, i * 24 + 24);
		const data = word.subarray(0, 12);
		golayDecode12(data, word.subarray(12));
		words.set(data.subarray(0, 6), (23 - 2 * i) * 6);
		words.set(data.subarray(6), (22 - 2 * i) * 6);
	}
	const data = words.subarray(72);
	if (rsDecode_24_12_13(data, words.subarray(0, 72)) === 0) linkControl(wireOrder(data), status);
}
